name: Rust

on:
  pull_request:

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Format
      run: cargo fmt -- --check
    - name: Build
      run: cargo build
